# .github/workflows/build-project.yml
name: Build Project

on:
  workflow_run:
    workflows: ["Install Dependencies"]  # Dependent on the install dependencies workflow
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build project
        run: npm run build
