name: Build and Deploy to InfinityFree

on:
  push:
    branches:
      - main # Adjust if you're using another branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or your desired version of Node.js

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (e.g. React, Angular, etc.)
      - name: Build project
        run: npm run build

      # Deploy to InfinityFree via FTP
      - name: Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          ftp-server: ftpupload.net
          ftp-username: if0_38377025
          ftp-password: Worldstar123
          local-dir: ./dist # Make sure this matches your build output
          remote-dir: /htdocs # Path where you want to deploy in InfinityFree
