# .github/workflows/deploy-infinityfree.yml
name: Deploy to InfinityFree

on:
  workflow_run:
    workflows: ["Build Project"]  # Dependent on the build project workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftpupload.net
          username: if0_38377025
          password: Worldstar123
          local-dir: ./react/dist/ # Make sure this matches your build output
          server-dir: /htdocs/ # Path where you want to deploy in InfinityFree
