name: Build and Deploy to InfinityFree

on:
  push:
    branches:
      - main # Adjust if you're using another branch

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Or your desired version of Node.js

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (e.g. React, Angular, etc.)
      - name: Build project
        run: npm run build

      - name: Verify Build Directory
        run: ls -la dist || echo "⚠️ react/dist directory not found!"

      # Authenticate Firebase CLI using Service Account JSON
      - name: Authenticate Firebase CLI
        run: |
          echo '{
            "type": "service_account",
            "project_id": "your-project-id",
            "private_key_id": "your-private-key-id",
            "private_key": "-----BEGIN PRIVATE KEY-----YOUR-PRIVATE-KEY-----END PRIVATE KEY-----",
            "client_email": "firebase-adminsdk-xxxxx@your-project-id.iam.gserviceaccount.com",
            "client_id": "your-client-id",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-xxxxx%40your-project-id.iam.gserviceaccount.com"
          }' > $HOME/firebase-key.json
        shell: bash

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: react/dist  # Deploy 'dist' contents to root of 'gh-pages'
      #     keep_files: false  # Remove old files before deploying
      #     force_orphan: true  # Overwrite all commits, keeping only the latest

# 1//0guFOO3Q4wkF8CgYIARAAGBASNwF-L9IrRs-B2B84xsKFrUPIJVRvsC9y0Ur3hw8hFCpJpwljRfY0aQeCDLIQR_Pat8WkNOm8Yn4
          
      # # Deploy to InfinityFree via FTP
      # - name: Deploy to InfinityFree
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ftpupload.net
      #     username: if0_38377025
      #     password: Worldstar123
      #     local-dir: ./react/dist/ # Make sure this matches your build output
      #     server-dir: /htdocs/ # Path where you want to deploy in InfinityFree
