# .github/workflows/install-dependencies.yml
name: Install Dependencies

on:
  workflow_run:
    workflows: ["Set up Node.js"]  # Dependent on the node setup workflow
    types:
      - completed

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install
